# deploy Maven artifacts to Sonatype OSS repo
language: java

jdk:
  - openjdk6

# whitelist
branches:
  only:
    - master

# checkout settings
before_install: 
  - "git clone -b master https://github.com/molindo/travis-settings.git target/travis-settings"
  - "target/travis-settings/tasks/before_install.sh"

# install and deploy
install: "target/travis-settings/tasks/install.sh"
script:  "target/travis-settings/tasks/script.sh"

# travis encrypt 'token@room'
notifications:
  hipchat: 
    - secure: "CQYrf5T7Fjb0QvmC5ushZNvNC/3FqhmC5IREAcbK5Sb9cLztT2YKC3b+IM8fjoSqWOD0/ht4aXtYfWVqN4vstfu9DxpUP67kLmYuZbkb7KNjMjrFJ0/CcqXPIZPCbwT1fEvttqyAZjwtzZY19KvHAdj47VvYeOnxm7OmKwDzpBM="

# travis encrypt 'CI_DEPLOY_USERNAME=username'
# travis encrypt 'CI_DEPLOY_PASSWORD=password'
env:
  global:
    - secure: "J2FjTG14l2spN4ezfdMLIRMi3tf4/6DIBuP+uTglRaHI2xayc+KESUew86u1We3NGTfpq8ZnBQ4mQepJJM1KqElGdh7rzVIcfxgfebK3X3mP4+IUA/afdftWpsToAltbi/mBXrpAJjXXV8+XrSRN/Z0b51//bi+QYR88OltIFpU="
    - secure: "Z/TSamjTzDMw0bIuHKqgFjmSFCctiu+RWJ22k7t+fiOTDOXHoknQTeBhc6Ic2cPpt91qHYFvqhQGDeEPG1nZr1aSSrExlMNUCtcDcl/jNHapOblSm9T4fHkDn4gzhpAaIZO6o4h2HhQzbjGp9kd418S4kLO9tfUr4vPTh859vhs="

