# deploy Maven artifacts to Sonatype OSS repo
language: java

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

# whitelist
branches:
  only:
    - master

# checkout settings
before_install: 
  - "git clone -b master https://github.com/molindo/travis-settings.git target/travis-settings"
  - "target/travis-settings/tasks/before_install.sh"

# install and deploy
install: "target/travis-settings/tasks/install.sh"
script:  "target/travis-settings/tasks/script.sh"

# travis encrypt 'token@room'
notifications:
  email: false
  hipchat: 
    rooms:
      - secure: "TMmMOU/XX0iPXs5v5/0h9P7co5WhssE76HncvdbwFJ1KOzp+sd7Zcmv/GSBdGdyucYJ/vKWr5AYZQnrlHX1+m5VPrXlC+cG3QbqLloc0gDQikTcFyQNg8sCFKyaOXU89nY7cirp6lDn6kliP+sJs+lwg6q1nTwPO0GE1uCa220c="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    on_success: always
    on_failure: always

# travis encrypt 'CI_DEPLOY_USERNAME=username'
# travis encrypt 'CI_DEPLOY_PASSWORD=password'
env:
  global:
    - secure: "Ny5l/SoYmEIEkqqb9NzN/qjUhE9vabYuE3Wx5oa/RA+wjP1178U26wwtzmfzJHcR50MQX/MNqra/ZmaW5qrw4stl3+vUCSVJ3CTUtmoZuMdULgvt2tXVmBchWjL0oa4RNZYpp5L+XeNHoKwDaWeBsvvifyVW+aMaXmeW5Zk7EeI="
    - secure: "UOQ1/193TOSQ6i1navF9pcOcBdxY9f+q23yK7+248F62MPP2dvivV9l306UiyXRJ/aUauVm+92u8+aL2wLk4BZVQ/bT99tf8zmguqNZXsg5g8BcBhsIklpbfLqtKyxReXxBNEFw+LmkV+heDJU6IcUMnHUFa+chIxqdZHL6tpos="
